#' Export PAVER results to a formatted data frame
#'
#' This function takes a PAVER result object and prepares it for export as a wide format
#' data frame. The resulting data frame will have GO Term IDs, Definitions, generated themes, and columns
#' for each of the groups in the PAVER result, with values representing the original input value
#' of each GO term for that group.
#'
#' @param PAVER_result A PAVER result object generated by the \code{\link{generate_themes}} function.
#' @return A wide format data frame with GO Term IDs, Definitions, generated themes, and columns
#' for each of the groups in the PAVER result, with values representing the original input value
#' of each GO term for that group.
#'
#' @examples
#' TRUE
#'
#' @export
PAVER_export <- function(PAVER_result) {
  result <- PAVER_result$prepared_data %>%
    dplyr::select(.data$GOID, .data$Group, .data$value) %>%
    dplyr::inner_join(PAVER_result$clustering %>%
      dplyr::select(.data$GOID, .data$Cluster) %>%
      dplyr::distinct(.data$GOID, .keep_all = T), by = "GOID") %>%
    dplyr::inner_join(PAVER_result$goterms_df, by = "GOID") %>%
    tidyr::pivot_wider(names_from = .data$Group, values_from = .data$value) %>%
    dplyr::mutate(dplyr::across(
      .cols = c(!.data$GOID, !.data$Cluster, !.data$Term),
      .fns = ~ tidyr::replace_na(.x, 0)
    ))

  result
}
